#-------------------------------
# Site Settings

title: Soyeon Jeon
logo: # You can add own logo. For example '/images/logo.png'.
description: Avenco – Creative Portfolio Theme for Jekyll

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Teaching'
      url: '/teaching/'
    - title: 'Pages'
      submenu:
      - url: '/about'
        title: 'About'
      - url: '/elements'
        title: 'Elements'

# Call to action button
cta__button__text: Get in touch

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/37.jpg'


#-------------------------------
# Author Settings

author:
  name: Soyeon Jeon
  title: Hello I’m Soyeon!
  bio: "I am a Ph.D. student in Political Science and an A.M. student in Statistics and Data Science at Washington University in St. Louis. I am interested in Computational Social Science and Political Communication. When I'm not working, 404 not found."
  image: '/images/01.jpg'
  avatar: '/images/avatar.jpg'
  button__text: Download my CV


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Working <span class="text-span">Paper</span> # Add a 'text-span' class to highlight text.
  projects__description: I study detecting bias in LLMs/VLMs and analyzing voters' behavior using these models.


#-------------------------------
# Testimonials Section

testimonial__title: My Happy <span class="text-span">Committee</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Jacob Montgomery"
    image: "/images/client-1.jpg"
    designation: "Professor"
    content: "Professor Montgomery's research focuses on how to use advanced methods from statistics and computer science for core social science tasks with a focus on American politics and social media."
    url: https://polisci.wustl.edu/people/jacob-montgomery

  - name: "Christopher Lucas"
    image: "/images/client-2.jpg"
    designation: "Associate Professor"
    content: "Professor Lucas studies methodology, political communication, and the media. He has received the Gosnell Prize for Excellence in Political Methodology twice and multiple grants from the NSF."
    url: https://polisci.wustl.edu/people/christopher-lucas


  - name: "Taylor Carlson"
    image: "/images/client-3.jpg"
    designation: "Associate Professor"
    content: "Professor Carlson studies American Politics with a focus on political communication and political psychology, specifically content, process, and consequences of interpersonal political communication."
    url: https://polisci.wustl.edu/people/taylor-carlson

  - name: "Betsy Sinclair"
    image: "/images/client-4.jpg"
    designation: "Department Chair, Professor"
    content: "​Professor Sinclair’s research interests include American politics and political methodology with an emphasis on individual political behavior, especially social foundations of participatory democracy."
    url: https://polisci.wustl.edu/people/betsy-sinclair


#-------------------------------
# Teaching Section

blog__settings:
  blog__title: Recent <span class="text-span">News</span> # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: your@email.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Avenco comes with a built-in contact form. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://x.com/soyeon_polisci"}
- {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-pinterest", link: "https://www.linkedin.com/in/soyeon-jeon-polisci/"} # linked-in
- {icon: "ion-logo-codepen", link: "https://codepen.io"} # email
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com"} # orcid: https://orcid.org/0009-0003-7672-8946
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
